### ISSUE TITLE
Could not find JarLauncher from jar

### ISSUE THREAD

**Issue by jakubriegel** [scotthaleen/clojure-spring-cloud#4]
Runnig `lein spring-boot-jar` then `java -jar target/boot-spring-cloud-0.1.0-SNAPSHOT.jar` results in following error:
```
Error: Could not find or load main class org.springframework.boot.loader.JarLauncher
```
The `.class` file for `JarLauncher` actually are in `target` dir. 

Is there a fix for that?

**Comment by jakubriegel** [comment]
The issue is present only on Windows. Building it on Debian was successful.

**Comment by scotthaleen** [comment]
Thank you for the feedback unfortunately I do not have access to Windows to test it out.  Likely there may be some issues with the PATH setup.
